name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  INSTANCE_ID: i-078df5aaf60b81eb8

jobs:
  deploy:
    runs-on: aws

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Create deployment archive
        run: |
          tar -czf app.tar.gz .

      - name: Upload archive to S3
        run: |
          aws s3 cp app.tar.gz s3://<YOUR_BUCKET>/deployments/app.tar.gz

      - name: Deploy on EC2
        run: |
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "mkdir -p /home/ec2-user/app",
              "aws s3 cp s3://<YOUR_BUCKET>/deployments/app.tar.gz /tmp/app.tar.gz",
              "rm -rf /home/ec2-user/app/*",
              "tar -xzf /tmp/app.tar.gz -C /home/ec2-user/app",
              "chown -R ec2-user:ec2-user /home/ec2-user/app"
            ]'
